name: Generate bounties data
run-name: ${{ github.actor }} 🚀
on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'

env:
  ALCHEMY_APIKEY: ${{ secrets.ALCHEMY_APIKEY }}
  ALCHEMY_APIKEY_2: ${{ secrets.ALCHEMY_APIKEY_2 }}
  INFURA_APIKEY: ${{ secrets.INFURA_APIKEY }}

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v2
        with:
          go-version: '1.22.1'

      - run: go run ./main.go bounties

      - name: Update from main
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Automation"
          git config pull.rebase false
          git checkout main
          git add .
          git commit -m "Bounties"
          git pull
          git merge --strategy=ours origin/main
          git push
        shell: bash
        if: always()

