name: Checkpoint Gauges

on:
  schedule:
    - cron: "30 0 * * 4"
  workflow_dispatch:      

env:
  ALCHEMY_APIKEY: ${{ secrets.ALCHEMY_APIKEY }}
  ALCHEMY_APIKEY_2: ${{ secrets.ALCHEMY_APIKEY_2 }}
  INFURA_APIKEY: ${{ secrets.INFURA_APIKEY }}
  ALCHEMY_APIKEY_3: ${{ secrets.ALCHEMY_APIKEY_3 }}
  TENDERLY_NODE: ${{ secrets.TENDERLY_NODE }}
  FORK_PK: ${{ secrets.FORK_PK }}
  TENDERLY_SLUG: ${{ secrets.TENDERLY_SLUG }}
  TENDERLY_PROJECT_SLUG: ${{ secrets.TENDERLY_PROJECT_SLUG }}
  TENDERLY_ACCESS_KEY: ${{ secrets.TENDERLY_ACCESS_KEY }}
  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
  DRPC_API_KEY: ${{ secrets.DRPC_API_KEY }}
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

jobs:
  checkpoint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v2
        with:
          go-version: '1.23.4'

      - run: go run ./main.go checkpoint ALCHEMY_APIKEY_3