name: Generate gauges data
run-name: ${{ github.actor }} 🚀
on:
  workflow_dispatch:
  schedule:
    - cron: '*/50 * * * *'

env:
  ALCHEMY_APIKEY: ${{ secrets.ALCHEMY_APIKEY }}
  ALCHEMY_APIKEY_2: ${{ secrets.ALCHEMY_APIKEY_2 }}
  INFURA_APIKEY: ${{ secrets.INFURA_APIKEY }}

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v2
        with:
          go-version: '1.22.1'

      - run: go run ./main.go gauges

      - run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Automation"
          git checkout main
          git pull
          git checkout ${{github.ref_name}}
          git pull
        shell: bash
        if: always()

      - name: Commit and push changes to repo
        run: |
          git config user.email "actions@github.com"
          git config user.name "crvhub"
          git config pull.rebase false
          git pull
          git add .
          git commit -m "Gauges"
          git merge --strategy=ours origin/main
          git pull
          git push
        shell: bash
        if: always()

